#!/bin/sh
if [ -z "${1}" ] ; then
  echo "Usage: $0 playlist.lst."
  echo "This will convert playlists from mp3blaster-versions prior to 2.0b8"
  echo "to 2.0b8 compatible lists."
  exit 1
fi

if [ -f "${1}.new" ] ; then
  echo "${1}.new exists, bailing out."
  exit 1
fi

echo "GLOBALMODE: allgroups"
while read line ; do
  echo $line
  if test "`echo $line|egrep '^GROUPNAME:'`" != "" ; then
    echo "PLAYMODE: 0"
  fi
done < ${1}
