#ifndef _MY_GENRE_TAB
#define _MY_GENRE_TAB
#if 0
struct _genre_table
{
  int genre;
  char *text;
} genre_table [] =
{
{0,"Blues"},
{1,"Classic Rock"},
{2,"Country"},
{3,"Dance"},
{4,"Disco"},
{5,"Funk"},
{6,"Grunge"},
{7,"Hip-Hop"},
{8,"Jazz"},
{9,"Metal"},
{10,"New Age"},
{11,"Oldies"},
{12,"Other"},
{13,"Pop"},
{14,"R&B"},
{15,"Rap"},
{16,"Reggae"},
{17,"Rock"},
{18,"Techno"},
{19,"Industrial"},
{20,"Alternative"},
{21,"Ska"},
{22,"Death Metal"},
{23,"Pranks"},
{24,"Soundtrack"},
{25,"Eurotechno"},
{26,"Ambient"},
{27,"Trip-Hop"},
{28,"Vocal"},
{29,"Jazz+Funk"},
{30,"Fusion"},
{31,"Trance"},
{32,"Classical"},
{33,"Instrumental"},
{34,"Acid"},
{35,"House"},
{36,"Game"},
{37,"Sound Clip"},
{38,"Gospel"},
{39,"Noise"},
{40,"Alternative Rock"},
{41,"Bass"},
{42,"Soul"},
{43,"Punk"},
{44,"Space"},
{45,"Meditative"},
{46,"Instrumental Pop"},
{47,"Instrumental Rock"},
{48,"Ethnic"},
{49,"Gothic"},
{50,"Darkwave"},
{51,"Techno-Industrial"},
{52,"Electronic"},
{53,"Pop-Folk"},
{54,"Eurodance"},
{55,"Dream"},
{56,"Southern Rock"},
{57,"Comedy"},
{58,"Cult"},
{59,"Gangsta"},
{60,"Top 40"},
{61,"Christian Rap"},
{62,"Pop/Funk"},
{63,"Jungle"},
{64,"Native American"},
{65,"Cabaret"},
{66,"New Wave"},
{67,"Psychadelic"},
{68,"Rave"},
{69,"Show Tunes"},
{70,"Trailer"},
{71,"Lo-Fi"},
{72,"Tribal"},
{73,"Acid Punk"},
{74,"Acid Jazz"},
{75,"Polka"},
{76,"Retro"},
{77,"Musical"},
{78,"Rock & Roll"},
{79,"Hard Rock"},
{80,"Folk"},
{81,"Folk/Rock"},
{82,"National Folk"},
{83,"Swing"},
{84,"Fast-Fusion"},
{85,"Bebop"},
{86,"Latin"},
{87,"Revival"},
{88,"Celtic"},
{89,"Bluegrass"},
{90,"Avantgarde"},
{91,"Gothic Rock"},
{92,"Progressive Rock"},
{93,"Psychedelic Rock"},
{94,"Symphonic Rock"},
{95,"Slow Rock"},
{96,"Big Band"},
{97,"Chorus"},
{98,"Easy Listening"},
{99,"Acoustic"},
{100,"Humour"},
{101,"Speech"},
{102,"Chanson"},
{103,"Opera"},
{104,"Chamber Music"},
{105,"Sonata"},
{106,"Symphony"},
{107,"Booty Bass"},
{108,"Primus"},
{109,"Porn Groove"},
{110,"Satire"},
{111,"Slow Jam"},
{112,"Club"},
{113,"Tango"},
{114,"Samba"},
{115,"Folklore"},
{116,"Ballad"},
{117,"Power Ballad"},
{118,"Rhytmic Soul"},
{119,"Freestyle"},
{120,"Duet"},
{121,"Punk Rock"},
{122,"Drum Solo"},
{123,"Acapella"},
{124,"Euro-House"},
{125,"Dance Hall"},
{126,"Goa"},
{127,"Drum & Bass"},
{128,"Club-House"},
{129,"Hardcore"},
{130,"Terror"},
{131,"Indie"},
{132,"BritPop"},
{133,"Negerpunk"},
{134,"Polsk Punk"},
{135,"Beat"},
{136,"Christian Gangsta Rap"},
{137,"Heavy Metal"},
{138,"Black Metal"},
{139,"Crossover"},
{140,"Contemporary Christian"},
{141,"Christian Rock"},
{256,NULL}
};
#endif
char *genre_table[] = {
	"Blues",		//0
	"Classic Rock",
	"Country",
	"Dance",
	"Disco",
	"Funk",
	"Grunge",
	"Hip-Hop",
	"Jazz",
	"Metal",
	"New Age",		//10
	"Oldies",
	"Other",
	"Pop",
	"R&B",
	"Rap",
	"Reggae",
	"Rock",
	"Techno",
	"Industrial",
	"Alternative",	//20
	"Ska",
	"Death Metal",
	"Pranks",
	"Soundtrack",
	"Eurotechno",
	"Ambient",
	"Trip-Hop",
	"Vocal",
	"Jazz+Funk",
	"Fusion",		//30
	"Trance",
	"Classical",
	"Instrumental",
	"Acid",
	"House",
	"Game",
	"Sound Clip",
	"Gospel",
	"Noise",
	"Alternative Rock",	//40
	"Bass",
	"Soul",
	"Punk",
	"Space",
	"Meditative",
	"Instrumental Pop",
	"Instrumental Rock",
	"Ethnic",
	"Gothic",
	"Darkwave",		//50
	"Techno-Industrial",
	"Electronic",
	"Pop-Folk",
	"Eurodance",
	"Dream",
	"Southern Rock",
	"Comedy",
	"Cult",
	"Gangsta",
	"Top 40",	//60
	"Christian Rap",
	"Pop/Funk",
	"Jungle",
	"Native American",
	"Cabaret",
	"New Wave",
	"Psychadelic",
	"Rave",
	"Show Tunes",
	"Trailer",	//70
	"Lo-Fi",
	"Tribal",
	"Acid Punk",
	"Acid Jazz",
	"Polka",
	"Retro",
	"Musical",
	"Rock & Roll",
	"Hard Rock",
	"Folk",		//80
	"Folk/Rock",
	"National Folk",
	"Swing",
	"Fast-Fusion",
	"Bebop",
	"Latin",
	"Revival",
	"Celtic",
	"Bluegrass",
	"Avantgarde",	//90
	"Gothic Rock",
	"Progressive Rock",
	"Psychedelic Rock",
	"Symphonic Rock",
	"Slow Rock",
	"Big Band",
	"Chorus",
	"Easy Listening",
	"Acoustic",
	"Humour",		//100
	"Speech",
	"Chanson",
	"Opera",
	"Chamber Music",
	"Sonata",
	"Symphony",
	"Booty Bass",
	"Primus",
	"Porn Groove",
	"Satire",		//110
	"Slow Jam",
	"Club",
	"Tango",
	"Samba",
	"Folklore",
	"Ballad",
	"Power Ballad",
	"Rhytmic Soul",
	"Freestyle",
	"Duet",			//120
	"Punk Rock",
	"Drum Solo",
	"Acapella",
	"Euro-House",
	"Dance Hall",
	"Goa",
	"Drum & Bass",
	"Club-House",
	"Hardcore",
	"Terror",		//130
	"Indie",
	"BritPop",
	"Negerpunk",
	"Polsk Punk",
	"Beat",
	"Christian Gangsta Rap",
	"Heavy Metal",
	"Black Metal",
	"Crossover",
	"Contemporary Christian",	//140
	"Christian Rock",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//150
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//160
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//170
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//180
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//190
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//200
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//210
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//220
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//230
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//240
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",	//250
	"Unknown",
	"Unknown",
	"Unknown",
	"Unknown",
	NULL
};
#else
#if 0
extern struct _genre_table
{
	int genre;
	char text[41];
} genre_table;
#endif
extern char *genre_table[];

#endif
